version: '3.8'

services:
  # --------------------
  # 0. Nginx 反向代理服务
  # --------------------
  nginx:
    image: nginx:stable-alpine # 使用轻量级的 Nginx 镜像
    container_name: comic7_nginx
    ports:
      - "5000:80" # 将主机 5000 端口映射到 Nginx 的 80 端口
    volumes:
      # 挂载自定义的 Nginx 配置文件
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # 挂载 Nginx 缓存目录（用于proxy_cache）
      - nginx_cache:/var/cache/nginx
      # 挂载媒体目录，让 Nginx 可以直接访问视频文件
      # - "F:\\games\\comics:/comics:ro"
      - "F:\\games\\comics\\photograph:/comics:ro"
    depends_on:
      - web # 确保 Nginx 在 web 服务启动后才启动
      
  # --------------------
  # 1. Flask 应用服务 (web)
  # --------------------
  web:
    build: 
      context: .
    container_name: comic7_server
      
    volumes:
      - ./:/app
      # - "F:\\games\\comics:/comics:ro"
      - "F:\\games\\comics\\photograph:/comics" 
      
    depends_on:
      - redis
      
    environment:
      REDIS_HOST: redis
      BASE_DIR: /comics 

  # --------------------
  # 2. Redis 缓存服务
  # --------------------
  redis:
    image: redis:7-alpine 
    container_name: comic7_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 

volumes:
  redis_data:
  nginx_cache: # 新增 Nginx 缓存卷