server:
  port: 500
comic:
  root-dir: ${COMICS_ROOT_DIR:F:\games\comics}
  hq-sub-dir: ${HQ_SUB_DIR:h_photograph}
  cache-expiration: ${CACHE_EXPIRATION:604800}

spring:
  application:
    name: comic
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 1
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: info